import React from 'react';

interface LegalModalProps {
  isOpen: boolean;
  type: 'privacy' | 'terms';
  onClose: () => void;
}

export const LegalModal: React.FC<LegalModalProps> = ({ isOpen, type, onClose }) => {
  if (!isOpen) return null;

  const isPrivacy = type === 'privacy';

  return (
    <div className="fixed inset-0 z-[70] flex items-center justify-center p-4 bg-slate-900/70 backdrop-blur-sm">
      <div className="bg-white rounded-2xl border border-slate-200 shadow-2xl w-full max-w-2xl max-h-[85vh] flex flex-col overflow-hidden">
        {/* Header */}
        <div className="px-6 py-4 border-b border-slate-200 flex items-center justify-between bg-gradient-to-r from-slate-900 to-slate-800 text-white">
          <div className="flex items-center gap-2.5">
            <span className="material-symbols-outlined text-blue-300 text-xl">
              {isPrivacy ? 'shield_with_heart' : 'gavel'}
            </span>
            <div>
              <h2 className="font-bold text-sm">
                {isPrivacy ? 'Privacy Policy' : 'Terms of Service'}
              </h2>
              <p className="text-[11px] text-slate-400 font-code-mono">
                medi AI / SastaRx Platform · Effective 2026-09-09
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded-lg text-slate-400 hover:text-white hover:bg-white/10 cursor-pointer transition-colors"
          >
            <span className="material-symbols-outlined text-lg">close</span>
          </button>
        </div>

        {/* Body */}
        <div className="p-6 overflow-y-auto flex-1 text-sm text-slate-700 leading-relaxed space-y-5">
          {isPrivacy ? <PrivacyContent /> : <TermsContent />}
        </div>

        {/* Footer */}
        <div className="px-6 py-3 border-t border-slate-200 bg-slate-50 flex justify-end">
          <button
            onClick={onClose}
            className="px-5 py-2 rounded-lg bg-[#2563EB] hover:bg-blue-700 text-white font-semibold text-xs cursor-pointer transition-colors"
          >
            I Understand
          </button>
        </div>
      </div>
    </div>
  );
};

// ─── Privacy Policy Content ───────────────────────────────────────────────────

const PrivacyContent: React.FC = () => (
  <>
    <section>
      <h3 className="font-bold text-base text-slate-900 mb-2">1. Data Controller</h3>
      <p>
        medi AI / SastaRx Ops &amp; Discovery Platform is operated by SastaRx Technologies Pvt. Ltd.
        For data-related queries, contact: <strong>privacy@sastarx.in</strong>
      </p>
    </section>

    <section>
      <h3 className="font-bold text-base text-slate-900 mb-2">2. Data We Collect</h3>
      <ul className="list-disc pl-5 space-y-1 text-slate-600">
        <li><strong>Account data:</strong> name, email, role, medical licence number, department.</li>
        <li><strong>Session data:</strong> JWT authentication tokens stored in browser local storage.</li>
        <li><strong>Clinical activity:</strong> audit log entries generated by formulary and pricing actions.</li>
        <li><strong>Prescription images:</strong> when uploaded for AI-OCR, processed transiently — not stored permanently.</li>
      </ul>
    </section>

    <section>
      <h3 className="font-bold text-base text-slate-900 mb-2">3. How We Use Data</h3>
      <ul className="list-disc pl-5 space-y-1 text-slate-600">
        <li>Providing authenticated clinical operations and patient discovery features.</li>
        <li>Generating tamper-evident audit trails for DISHA/HIPAA compliance.</li>
        <li>Improving generic bioequivalence data accuracy and platform reliability.</li>
      </ul>
    </section>

    <section>
      <h3 className="font-bold text-base text-slate-900 mb-2">4. Data Retention</h3>
      <p className="text-slate-600">
        Audit logs are retained for a minimum of <strong>7 years</strong> per DISHA Section 7 requirements.
        Account data is retained for the duration of the contractual relationship plus 2 years.
        Prescription images submitted for OCR are not persisted after processing.
      </p>
    </section>

    <section>
      <h3 className="font-bold text-base text-slate-900 mb-2">5. Data Security</h3>
      <ul className="list-disc pl-5 space-y-1 text-slate-600">
        <li>All data at rest and in transit is encrypted (AES-256 / TLS 1.3).</li>
        <li>Multi-tenant Row-Level Security (PostgreSQL RLS) ensures strict data isolation.</li>
        <li>HMAC-SHA256 signed audit logs provide tamper evidence.</li>
        <li>Passwords are hashed with bcrypt (cost factor 12). Plain-text passwords are never stored.</li>
      </ul>
    </section>

    <section>
      <h3 className="font-bold text-base text-slate-900 mb-2">6. AI Processing &amp; Third Parties</h3>
      <p className="text-slate-600">
        AI features (prescription OCR, medicine recommendations, dispute triage) use the Google Gemini API.
        API calls are made server-side only — your GEMINI_API_KEY is never exposed to the browser.
        Google's data processing terms apply to any data transmitted to the Gemini API.
      </p>
    </section>

    <section>
      <h3 className="font-bold text-base text-slate-900 mb-2">7. Your Rights (DISHA / GDPR)</h3>
      <ul className="list-disc pl-5 space-y-1 text-slate-600">
        <li>Right to access your personal data.</li>
        <li>Right to rectification of inaccurate data.</li>
        <li>Right to erasure (where legally permissible — audit logs are exempt).</li>
        <li>Right to data portability in machine-readable format.</li>
      </ul>
    </section>

    <p className="text-xs text-slate-400 font-code-mono pt-2 border-t border-slate-100">
      Compliant with: DISHA (Digital Information Security in Healthcare Act, India) ·
      HIPAA (Health Insurance Portability and Accountability Act, USA) ·
      GDPR (General Data Protection Regulation, EU)
    </p>
  </>
);

// ─── Terms of Service Content ─────────────────────────────────────────────────

const TermsContent: React.FC = () => (
  <>
    <section>
      <h3 className="font-bold text-base text-slate-900 mb-2">1. Acceptance of Terms</h3>
      <p>
        By accessing or using the medi AI / SastaRx platform, you agree to be bound by these Terms.
        If you do not agree, do not use the platform.
      </p>
    </section>

    <section>
      <h3 className="font-bold text-base text-slate-900 mb-2">2. Intended Use</h3>
      <p className="text-slate-600">
        This platform is intended for licensed healthcare professionals, pharmacists, and patients seeking
        generic medicine information. It is <strong>not</strong> a substitute for professional medical advice,
        diagnosis, or treatment. All substitution decisions must involve a licensed prescribing physician.
      </p>
    </section>

    <section>
      <h3 className="font-bold text-base text-slate-900 mb-2">3. Clinical Advisory</h3>
      <div className="p-3 rounded-lg bg-amber-50 border border-amber-200 text-amber-900 text-xs">
        <strong>Mandatory Disclaimer:</strong> Generic alternatives displayed are for informational purposes under CDSCO
        National Drug Guidelines. Always consult your prescribing physician before altering any medication regimen,
        particularly for narrow therapeutic index drugs (NTI medicines).
      </div>
    </section>

    <section>
      <h3 className="font-bold text-base text-slate-900 mb-2">4. AI-Generated Content</h3>
      <p className="text-slate-600">
        AI-powered features (OCR, recommendations, dispute triage) are decision-support tools.
        All AI outputs must be reviewed and verified by a qualified clinical professional before acting upon them.
        SastaRx Technologies is not liable for clinical decisions made solely on the basis of AI suggestions.
      </p>
    </section>

    <section>
      <h3 className="font-bold text-base text-slate-900 mb-2">5. Account Responsibilities</h3>
      <ul className="list-disc pl-5 space-y-1 text-slate-600">
        <li>You are responsible for maintaining the confidentiality of your credentials.</li>
        <li>Clinical roles (Lead Ops Admin, Clinical Pharmacist, etc.) carry corresponding professional obligations.</li>
        <li>Fraudulent registration or impersonation of licensed practitioners is prohibited and reportable to regulatory authorities.</li>
      </ul>
    </section>

    <section>
      <h3 className="font-bold text-base text-slate-900 mb-2">6. Intellectual Property</h3>
      <p className="text-slate-600">
        The medi AI platform, SastaRx brand, and all associated software are the intellectual property of
        SastaRx Technologies Pvt. Ltd. Generic medicine data is sourced from CDSCO, PMBI, and verified partner feeds.
      </p>
    </section>

    <section>
      <h3 className="font-bold text-base text-slate-900 mb-2">7. Limitation of Liability</h3>
      <p className="text-slate-600">
        To the maximum extent permitted by law, SastaRx Technologies is not liable for any indirect,
        incidental, or consequential damages arising from the use of this platform.
      </p>
    </section>

    <p className="text-xs text-slate-400 font-code-mono pt-2 border-t border-slate-100">
      Governing Law: Republic of India · Jurisdiction: Mumbai, Maharashtra ·
      Regulatory Oversight: CDSCO, Ministry of Health and Family Welfare
    </p>
  </>
);
